[GLOBAL]
pants_version = "2.8.1rc1"
backend_packages = [
  "pants.backend.shell",
  "pants.backend.python",
  "pants.backend.codegen.protobuf.python",
  "pants.backend.experimental.docker",
  "pants.backend.experimental.docker.lint.hadolint",
]

[source]
marker_filenames = ["setup.py", "main.py"]

[tailor]
ignore_paths = ["venv/**"]
ignore_adding_targets = ["venv"]

[anonymous-telemetry]
enabled = false